#verbosity: INFO

# to:   markdown-raw_html-native_divs-fenced_divs
# from: ipynb+implicit_figures+yaml_metadata_block
from: markdown+implicit_figures+raw_html-markdown_in_html_blocks+raw_attribute+inline_code_attributes+shortcut_reference_links+link_attributes
highlight-style: pygments
#highlight-style: tango

metadata:
  # pandoc-crossref
  autoEqnLabels: true
  # csl: style/citestyle.csl
  citeprgm: true
  styledir: ../style
  titlepage: title.tex
  institute: University of California, Berkeley
  geometry:
    - margin=1truein

variables:
  biblio-style: "authoryear"
  # My variables
  classicthesis: false
  # Pandoc variables
  fontsize: 11pt
  urlcolor: blue
  #documentclass: memoir
  #-----------------------
  #documentclass: scrbook
  #classoption:
  #- 'numbers=noenddot'
  #- 'BCOR=5mm'
  #- 'titlepage'
  #- 'headinclude=true'
  #- 'footinclude=true'
  #  #- 'cleardoublepage=empty'
  #  #- 'openright'
  #  #- 'twoside'
  #- 'abstract=on'
  #-----------------------
  documentclass: scrreprt
  classoption:
  - 'titlepage'
  # 'headinclude=true'
  - 'footinclude=true'
  #- 'cleardoublepage=empty'
  #- 'openright'
  - 'twoside'
  - 'abstract=off'
  #-----------------------

  ## Front matter
  #lof: true # list of figures
  #lot: true
  toc: true # table of contents
  toc-depth: 2
  # HTML
  monofont: inconsolata
  html-math-method:
    method: mathjax
    url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    # none, references, or javascript

#include-in-header: 
#  - ./style/extra-style.tex

# Bibliography
cite-method: biblatex
bibliography:
  - ./style/brace.bib

filters: 
  - pandoc-crossref
#   - ipynb_meta.lua
  - image_center.lua
#    - ipynb_html_output.lua
#atx-headers: true
top-level-division: chapter #part #part, chapter, section, default
# extract-media: img


